spring.application.name=event-management

spring.datasource.url=jdbc:postgresql://dpg-d72f35kg9agc7396m2lg-a.oregon-postgres.render.com/eventdb_za69
spring.datasource.username=goutham
spring.datasource.password=YsXNpMcOZgz8wGF00uJNrS8J0PNbSavo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true